"""Lockstep tests for ui_clone.check_inputs (B1).

These mechanically prove the two staleness locations (Python gate + bash
dispatcher) cannot diverge: they share ONE input map, ONE hasher, and ONE
sidecar-path deriver. The bash side reaches all three via the CLI, so we assert
the CLI output is byte-identical to the in-process import.
"""

from __future__ import annotations

import fnmatch
import re
import subprocess
import sys
from pathlib import Path

from ui_clone.check_inputs import (
    CHECK_INPUTS,
    all_known_check_ids,
    compute_check_input_hash,
    get_check_inputs,
    sidecar_path,
)

from ._helpers import _project_root


def _check_id_to_script() -> dict[str, str]:
    sh = (
        _project_root() / "skills" / "visual-debug" / "scripts" / "verification-plan.sh"
    ).read_text(encoding="utf-8")
    return dict(re.findall(r'add_check\s+"([^"]+)"\s*\\\s*\n\s*"([^"]+)"', sh))


def _add_check_ids() -> set[str]:
    sh = (
        _project_root() / "skills" / "visual-debug" / "scripts" / "verification-plan.sh"
    ).read_text(encoding="utf-8")
    return set(re.findall(r'add_check\s+"([^"]+)"', sh))


def _cli(*args: str) -> str:
    proc = subprocess.run(
        [sys.executable, "-m", "ui_clone.check_inputs", *args],
        cwd=str(_project_root()),
        capture_output=True,
        text=True,
        check=True,
    )
    return proc.stdout.strip()


def test_registry_completeness_matches_add_check_rows() -> None:
    """Every verification-plan.sh add_check id must be registered (so a new gate
    cannot ship without declaring inputs), and the registry must not carry
    phantom ids."""
    declared = _add_check_ids()
    registered = set(all_known_check_ids())
    assert declared, "no add_check rows parsed — parser/regex drift"
    missing = declared - registered
    extra = registered - declared
    assert not missing, f"check ids missing from CHECK_INPUTS registry: {sorted(missing)}"
    assert not extra, f"CHECK_INPUTS has ids with no add_check row: {sorted(extra)}"


def test_sidecar_path_cli_matches_import_and_is_flat() -> None:
    """The sidecar path is a pure function of check_id, identical via import and
    CLI, and FLAT (no path separator beyond the ref dir) even for ids that would
    be slash-bearing — the divergence hole the design review flagged."""
    ref = "/tmp/ref-x"
    for cid in sorted(all_known_check_ids()):
        imported = sidecar_path(ref, cid)
        via_cli = Path(_cli("sidecar", ref, cid))
        assert via_cli == imported, f"sidecar path diverged for {cid}"
        # Flat: the only path component under ref is the single sidecar filename.
        assert imported.parent == Path(ref), f"sidecar for {cid} escaped ref dir"
        assert "/" not in imported.name and "\\" not in imported.name


def test_sidecar_path_sanitizes_slash_bearing_id() -> None:
    """A future slash-bearing check_id must still yield a flat filename on both
    sides (structural fix for the produces-vs-check_id namespace collision)."""
    ref = "/tmp/ref-y"
    imported = sidecar_path(ref, "transitions/video-motion")
    assert imported.parent == Path(ref)
    assert "/" not in imported.name
    assert _cli("sidecar", ref, "transitions/video-motion") == str(imported)


def test_hash_cli_matches_import(tmp_path: Path) -> None:
    impl = tmp_path / "impl"
    ref = tmp_path / "ref"
    (impl / "src").mkdir(parents=True)
    (impl / "src" / "a.css").write_text(".a{color:red}\n")
    (impl / "package.json").write_text("{}\n")
    (ref / "sections").mkdir(parents=True)
    (ref / "bundle-map.json").write_text("{}\n", encoding="utf-8")
    (ref / "sections" / "matches.json").write_text("{}\n", encoding="utf-8")
    for cid in ("css-mirror", "hydration-check", "alignment-parity"):
        imported = compute_check_input_hash(str(impl), str(ref), cid)
        via_cli = _cli("hash", str(impl), str(ref), cid)
        # CLI prints EMPTY / UNREGISTERED sentinels; import returns ""/None.
        expected = {None: "UNREGISTERED", "": "EMPTY"}.get(imported, imported)
        assert via_cli == expected, f"hash diverged for {cid}"


def test_cli_sentinels() -> None:
    assert _cli("hash", "", "/tmp/none", "totally-unknown-check") == "UNREGISTERED"
    assert _cli("hash", "", "/tmp/none", "capacity-probe") == "EMPTY"
    assert _cli("hash", "", "/tmp/none", "css-mirror") == "UNAVAILABLE"
    assert _cli("mtime", "", "/tmp/none", "css-mirror") == "UNAVAILABLE"


# Ref artifacts regenerated by extract / decode / capture / section-compare. If a
# check's SCRIPT reads one of these, the registry must declare it as a ref input,
# or a regenerated ref artifact would silently reuse the check's stale verdict.
_SIGNIFICANT_REF = {
    "matches.json", "dom-scaffold.json", "visible-images.json", "transition-spec.json",
    "bundle-map.json", "asset-substitution.json", "regions.json", "section-map.json",
    "component-map.json", "animation-runtime-dump.json", "external-sdks.json",
    "bundle-extraction.json", "transition-coverage.json", "structure.json",
    "extracted.json", "scroll-engine.json", "interactions-detected.json",
    "detected-breakpoints.json", "generation-plan.json", "fonts.json", "head.json",
    "inline-svgs.json", "required-media.json", "canvas-webgl-detection.json",
    "assets.json", "svg-text-elements.json", "body-state.json", "design-bundles.json",
    "hover-css-rules.json", "animation-init-styles.json", "scroll-transitions.json",
    "runtime-text.json",
}
# The two proof-rollup plan dependencies have focused mutation tests in
# test_check_inputs.py. Keep the broad static script audit from requiring the
# plan for unrelated scripts that only mention dispatcher metadata.
_GLOBAL_ALLOW = {"verification-plan.json"}
# Per-check exceptions: artifact textually present in the script but NOT a real
# staleness input (only a comment, or the check writes it). Empty today — add
# WITH a justification comment if a future audit failure is a genuine false
# positive rather than a missing input.
_CHECK_ALLOW: dict[str, set[str]] = {}


def _ref_covers(check_id: str, name: str) -> bool:
    spec = get_check_inputs(check_id)
    assert spec is not None
    return any(fnmatch.fnmatch(name, g.split("/")[-1]) for g in spec.ref)


def test_registry_covers_significant_ref_artifacts_each_script_reads() -> None:
    """Systematic guard against too-narrow ref inputs (the silent stale-reuse
    class): every significant ref artifact a check's script references must be in
    that check's declared ref globs. A new ref-read added to a script without
    registering it fails here instead of shipping a false-green verdict."""
    mapping = _check_id_to_script()
    assert set(mapping) == set(CHECK_INPUTS), "add_check rows vs registry drift"
    problems: dict[str, list[str]] = {}
    for cid, script in mapping.items():
        p = _project_root() / script
        if not p.is_file():
            continue
        # Comment-stripped body so a `# reads foo.json` note is not a false read;
        # bare-name match catches artifacts referenced via shell arrays / loops
        # (not only `$REF_DIR/...` lines) — the blind spot a prior review found.
        body = "\n".join(line.split("#", 1)[0] for line in p.read_text(
            encoding="utf-8", errors="ignore"
        ).splitlines())
        allow = _GLOBAL_ALLOW | _CHECK_ALLOW.get(cid, set())
        reads = {
            n for n in _SIGNIFICANT_REF if re.search(rf"\b{re.escape(n)}\b", body)
        }
        missing = sorted(n for n in reads - allow if not _ref_covers(cid, n))
        if missing:
            problems[cid] = missing
    assert not problems, (
        "checks reading ref artifacts absent from their ref globs "
        f"(stale-reuse risk): {problems}"
    )
