"""Post-emit re-gate: no emitted module may import a file that does not exist.

Every driver has TWO independent predicates — one in scaffold_to_jsx.py deciding
whether App.tsx imports it, one in emit_scroll_helpers.py deciding whether the
file is written. Whenever a pair disagrees the generated project does not
compile, and nothing in the pipeline noticed: a clean scaffold of a 35/35-PASS
reference failed with "Could not resolve ./lib/ScrollLatchDriver".

Mirroring each predicate does not scale — there are ~12 driver imports across
three emitters (Next `@/lib/...`, vite `./lib/...`, and a third alias form), so
every pair would have to be kept in sync forever. This re-gate instead checks
GROUND TRUTH after emission: does the imported file exist on disk?
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
REGATE = ROOT / "skills" / "visual-debug" / "scripts" / "lib" / "regate_unresolved_imports.py"

# Every driver name the scaffold can import, across all three stacks.
DRIVER_NAMES = [
    "ScrollReveal",
    "ScrollScrub",
    "SmoothScroll",
    "ScrollStateDriver",
    "ScrollClassToggleDriver",
    "HoverClassToggleDriver",
    "ScrollLatchDriver",
    "ScrollLinkedStyleDriver",
    "SwiperActivator",
    "VideoAutoplayKick",
    "StateRevealDriver",
    "IOClassRevealDriver",
]


def _run(impl: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(REGATE), str(impl), *args],
        capture_output=True,
        text=True,
        timeout=60,
    )


def _impl_with_app(tmp_path: Path, app_body: str) -> Path:
    impl = tmp_path / "impl"
    (impl / "src" / "lib").mkdir(parents=True)
    (impl / "src" / "App.tsx").write_text(app_body, encoding="utf-8")
    return impl


def _app_importing(name: str, spec_prefix: str = "./lib/") -> str:
    return (
        "// Auto-generated by skills/visual-debug/scripts/scaffold-to-jsx.sh.\n"
        f"import {name} from '{spec_prefix}{name}';\n"
        "\n"
        "export default function App() {\n"
        "  return (\n"
        "    <div>\n"
        f"      <{name} />\n"
        "      <section>kept</section>\n"
        "    </div>\n"
        "  );\n"
        "}\n"
    )


@pytest.mark.parametrize("name", DRIVER_NAMES)
def test_dangling_driver_import_is_stripped_for_every_driver(
    tmp_path: Path, name: str
) -> None:
    """Per-instance proof that the class is closed, not just the latch case.

    Each driver is exercised with its file absent — the state its own gate pair
    produces when the two predicates disagree. The re-gate must remove both the
    import and the mount, leaving a tree that compiles.
    """
    impl = _impl_with_app(tmp_path, _app_importing(name))
    proc = _run(impl)

    assert proc.returncode == 0, proc.stdout + proc.stderr
    app = (impl / "src" / "App.tsx").read_text(encoding="utf-8")
    assert f"import {name}" not in app, app
    assert f"<{name} />" not in app, app
    assert "<section>kept</section>" in app, "unrelated markup must survive"
    assert name in proc.stderr, "removals must be reported, never silent"


def test_alias_specifier_is_resolved_against_src(tmp_path: Path) -> None:
    """The Next stack emits `@/lib/X`, which resolves to <impl>/src/lib/X."""
    impl = _impl_with_app(tmp_path, _app_importing("ScrollScrub", "@/lib/"))
    proc = _run(impl)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert "import ScrollScrub" not in (impl / "src" / "App.tsx").read_text(encoding="utf-8")


def test_resolvable_import_is_left_alone(tmp_path: Path) -> None:
    """A driver whose file exists must not be touched."""
    impl = _impl_with_app(tmp_path, _app_importing("SmoothScroll"))
    (impl / "src" / "lib" / "SmoothScroll.tsx").write_text("export default () => null;\n")
    proc = _run(impl)

    assert proc.returncode == 0, proc.stdout + proc.stderr
    app = (impl / "src" / "App.tsx").read_text(encoding="utf-8")
    assert "import SmoothScroll" in app
    assert "<SmoothScroll />" in app


def test_unresolvable_non_driver_import_fails_loudly(tmp_path: Path) -> None:
    """A dangling import that is NOT a known driver is a real bug.

    Stripping it would hide a genuine emitter fault, so the gate fails instead.
    This is the missing build check: it is what should have caught the latch
    defect before a 35/35-PASS reference shipped a non-compiling tree.
    """
    impl = _impl_with_app(
        tmp_path,
        "import Hero from './components/Hero';\n"
        "export default function App() { return <Hero />; }\n",
    )
    proc = _run(impl)

    assert proc.returncode != 0, proc.stdout + proc.stderr
    assert "Hero" in (proc.stdout + proc.stderr)


def test_check_mode_reports_without_editing(tmp_path: Path) -> None:
    """--check is the verification-plan row: report, never mutate."""
    impl = _impl_with_app(tmp_path, _app_importing("ScrollLatchDriver"))
    before = (impl / "src" / "App.tsx").read_text(encoding="utf-8")
    proc = _run(impl, "--check")

    assert proc.returncode != 0, proc.stdout + proc.stderr
    assert (impl / "src" / "App.tsx").read_text(encoding="utf-8") == before


def test_clean_tree_passes(tmp_path: Path) -> None:
    impl = _impl_with_app(
        tmp_path,
        "export default function App() { return <div>ok</div>; }\n",
    )
    proc = _run(impl)
    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_report_artifact_records_the_verdict(tmp_path: Path) -> None:
    """The plan row declares `produces`, so the check must write that artifact.

    Every other row writes evidence; staleness tracking reads it. A row with an
    empty `produces` would be the only unverifiable one in the plan.
    """
    import json

    impl = _impl_with_app(tmp_path, _app_importing("ScrollLatchDriver"))
    report = tmp_path / "ref" / "unresolved-imports.json"
    proc = _run(impl, "--check", "--report", str(report))

    assert proc.returncode != 0, proc.stdout + proc.stderr
    assert report.is_file(), "the declared artifact must be written"
    data = json.loads(report.read_text(encoding="utf-8"))
    assert data["status"] == "fail"
    assert any("ScrollLatchDriver" in entry for entry in data["unresolvedImports"])


def test_report_artifact_records_a_clean_pass(tmp_path: Path) -> None:
    import json

    impl = _impl_with_app(
        tmp_path, "export default function App() { return <div>ok</div>; }\n"
    )
    report = tmp_path / "ref" / "unresolved-imports.json"
    proc = _run(impl, "--check", "--report", str(report))

    assert proc.returncode == 0, proc.stdout + proc.stderr
    data = json.loads(report.read_text(encoding="utf-8"))
    assert data["status"] == "pass"
    assert data["unresolvedImports"] == []


def test_wrapper_usage_is_never_left_with_a_missing_import(tmp_path: Path) -> None:
    """Removing an import out from under a surviving reference is worse than
    the dangling import it replaces.

    ScrollReveal is used as a WRAPPER (`<ScrollReveal><X /></ScrollReveal>`),
    which the self-closing mount strip does not match. Stripping only the
    import leaves an undefined identifier — still unbuildable, now for a
    reason nothing reports. When any reference survives, fail loudly instead.
    """
    impl = _impl_with_app(
        tmp_path,
        "import ScrollReveal from './lib/ScrollReveal';\n"
        "export default function App() {\n"
        "  return <ScrollReveal><section>x</section></ScrollReveal>;\n"
        "}\n",
    )
    proc = _run(impl)

    assert proc.returncode != 0, proc.stdout + proc.stderr
    app = (impl / "src" / "App.tsx").read_text(encoding="utf-8")
    assert "import ScrollReveal" in app, (
        "the import must be left intact when it cannot be removed safely"
    )
    assert "still referenced" in (proc.stdout + proc.stderr)


@pytest.mark.parametrize(
    ("label", "source"),
    [
        ("re-export", "export { Thing } from './missing-reexport';\n"),
        ("star-re-export", "export * from './missing-star';\n"),
        ("dynamic-import", "const f = () => import('./missing-dynamic');\n"),
        ("require", "const r = require('./missing-require');\n"),
    ],
)
def test_every_module_specifier_form_is_checked(
    tmp_path: Path, label: str, source: str
) -> None:
    """A re-export or a dynamic import breaks the build exactly like a static
    one, so scanning only `import ... from` leaves real holes.

    Measured before this was closed: of five specifier forms, only `import type`
    was caught — re-exports, star re-exports, dynamic import() and require()
    all passed a clean verdict while pointing at files that do not exist.
    """
    impl = _impl_with_app(tmp_path, source + "export default function App() { return null; }\n")
    proc = _run(impl, "--check")

    assert proc.returncode != 0, f"{label} must be checked\n{proc.stdout}{proc.stderr}"
    assert "missing-" in (proc.stdout + proc.stderr)


def test_resolvable_reexport_and_dynamic_import_pass(tmp_path: Path) -> None:
    """The widened scan must not start failing on specifiers that DO resolve."""
    impl = _impl_with_app(
        tmp_path,
        "export { Thing } from './lib/Thing';\n"
        "const f = () => import('./lib/Thing');\n"
        "export default function App() { return null; }\n",
    )
    (impl / "src" / "lib" / "Thing.tsx").write_text("export const Thing = 1;\n", encoding="utf-8")
    proc = _run(impl, "--check")
    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_named_import_missing_from_resolved_module_fails_loudly(
    tmp_path: Path,
) -> None:
    """A module that RESOLVES can still lack the symbols asked of it.

    realfood-v4: MotionController imported ten scroll constants from
    `@/generated/motion-skeletons`, which emit-motion-skeletons.sh regenerates
    as `use*` hooks and has never exported a constant. The development compiler
    served HTTP 200 with import warnings, every binding was `undefined`, the
    first deref threw inside the effect, and every motion channel that controller
    owned was dead. The production build caught it later during type checking;
    this re-gate must fail earlier.
    """
    impl = _impl_with_app(
        tmp_path,
        "import { NAV_TOP_OUTPUT, useNavScrollStateMachine } from "
        "'@/generated/motion-skeletons';\n"
        "export default function App() { return <div>{NAV_TOP_OUTPUT}</div>; }\n",
    )
    (impl / "src" / "generated").mkdir(parents=True)
    (impl / "src" / "generated" / "motion-skeletons.ts").write_text(
        "export function useNavScrollStateMachine() { return 'hidden-at-top'; }\n",
        encoding="utf-8",
    )
    proc = _run(impl)

    assert proc.returncode == 3, proc.stdout + proc.stderr
    assert "NAV_TOP_OUTPUT" in proc.stderr
    assert "useNavScrollStateMachine" not in proc.stderr, (
        "the export that DOES exist must not be reported")


def test_named_import_present_in_resolved_module_passes(tmp_path: Path) -> None:
    """Exports declared any of the emitted ways are recognised."""
    impl = _impl_with_app(
        tmp_path,
        "import { A, B, C as D, type E } from '@/lib/params';\n"
        "export default function App() { return <div>{A}{B}{D}</div>; }\n",
    )
    (impl / "src" / "lib" / "params.ts").write_text(
        "export const A = [0, 100];\n"
        "function b() { return 1; }\n"
        "export { b as B };\n"
        "export class C {}\n"
        "export type E = string;\n",
        encoding="utf-8",
    )
    proc = _run(impl)
    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_whole_clause_type_import_is_not_checked_as_runtime_export(
    tmp_path: Path,
) -> None:
    """`import type { X }` is erased, including from `export { type X }` modules."""
    impl = _impl_with_app(
        tmp_path,
        "import type { Foo } from '@/lib/types';\n"
        "export default function App() { return <div>ok</div>; }\n",
    )
    (impl / "src" / "lib" / "types.ts").write_text(
        "type Foo = { value: string };\n"
        "export { type Foo };\n",
        encoding="utf-8",
    )

    proc = _run(impl, "--check")

    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_named_import_from_reexport_barrel_is_not_flagged(tmp_path: Path) -> None:
    """`export *` needs a full module graph to resolve — stay silent, not wrong."""
    impl = _impl_with_app(
        tmp_path,
        "import { Anything } from '@/components';\n"
        "export default function App() { return <div>{Anything}</div>; }\n",
    )
    (impl / "src" / "components").mkdir(parents=True)
    (impl / "src" / "components" / "index.ts").write_text(
        "export * from './Hero';\n", encoding="utf-8")
    (impl / "src" / "components" / "Hero.tsx").write_text(
        "export const Anything = 1;\n", encoding="utf-8")
    proc = _run(impl)
    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_named_import_does_not_treat_default_declaration_name_as_export(
    tmp_path: Path,
) -> None:
    """A default declaration's local name is not a named ESM export."""
    impl = _impl_with_app(
        tmp_path,
        "import { OnlyDefault } from '@/lib/OnlyDefault';\n"
        "export default function App() { return <OnlyDefault />; }\n",
    )
    (impl / "src" / "lib" / "OnlyDefault.tsx").write_text(
        "export default function OnlyDefault() { return null; }\n",
        encoding="utf-8",
    )

    proc = _run(impl)

    assert proc.returncode == 3, proc.stdout + proc.stderr
    assert "OnlyDefault" in proc.stderr


def test_named_import_accepts_every_exported_variable_declarator(
    tmp_path: Path,
) -> None:
    """All identifiers in one const declaration are named exports."""
    impl = _impl_with_app(
        tmp_path,
        "import { B } from '@/lib/params';\n"
        "export default function App() { return <div>{B}</div>; }\n",
    )
    (impl / "src" / "lib" / "params.ts").write_text(
        "export const A = [1, 2], B = { value: 'x,y' };\n",
        encoding="utf-8",
    )

    proc = _run(impl)

    assert proc.returncode == 0, proc.stdout + proc.stderr
